# Generated by Django 6.0.1 on 2026-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("status", models.IntegerField()),
                ("posting_date", models.TimeField()),
            ],
        ),
    ]
