# Generated by Django 6.0.1 on 2026-01-19 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("availability_status", models.BooleanField(default=True)),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Occupied_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "OccuipedTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ReleaseTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("availability_status", models.BooleanField(default=True)),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Occupied_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "OccuipedTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ReleaseTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectRomm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("availability_status", models.BooleanField(default=True)),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Occupied_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "OccuipedTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ReleaseTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("availability_status", models.BooleanField(default=True)),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Occupied_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "OccuipedTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ReleaseTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
