# Generated by Django 6.0.1 on 2026-01-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0002_conferenceroom_meetingroom_projectromm_trainingroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingroom",
            name="MainRoomName",
            field=models.CharField(default="", max_length=255),
        ),
    ]
