# Generated by Django 6.0.1 on 2026-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0004_chennairooms_delete_trainingroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chennairooms",
            name="availability_status",
            field=models.BooleanField(default=False),
        ),
    ]
