# Generated by Django 6.0.1 on 2026-01-20 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0005_alter_chennairooms_availability_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BangaloreRooms",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("MainRoomName", models.CharField(default="", max_length=255)),
                ("room_name", models.CharField(default="TR1", max_length=255)),
                ("capacity", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("availability_status", models.BooleanField(default=False)),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Occupied_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "OccuipedTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ReleaseTiming",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("BookedBy", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
