# Generated by Django 6.0.1 on 2026-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0006_bangalorerooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=255)),
                ("main_room_name", models.CharField(max_length=255)),
                ("booked_by", models.CharField(max_length=255)),
                ("occupied_by", models.CharField(max_length=255)),
                ("start_time", models.CharField(max_length=255)),
                ("end_time", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
