# Generated by Django 6.0.1 on 2026-01-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0007_bookinghistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("location_description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OfficeSeat",
            fields=[
                (
                    "seat_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "booked_by_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "booked_by_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("team_name", models.CharField(blank=True, max_length=100, null=True)),
                ("booking_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("release_time", models.TimeField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="Apis.seatblock",
                    ),
                ),
            ],
        ),
    ]
