# Generated by Django 6.0.1 on 2026-01-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0008_seatblock_officeseat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officeseat",
            name="block",
            field=models.CharField(default="Block 1", max_length=50),
        ),
        migrations.DeleteModel(
            name="SeatBlock",
        ),
    ]
