# Generated by Django 6.0.1 on 2026-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0009_alter_officeseat_block_delete_seatblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="managerAccess",
            field=models.BooleanField(default=False),
        ),
    ]
