# Generated by Django 6.0.1 on 2026-01-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0010_employees_manageraccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="chennairooms",
            name="FutureBookings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
