# Generated by Django 6.0.1 on 2026-01-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0011_chennairooms_futurebookings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chennairooms",
            name="FutureBookings",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
