# Generated by Django 6.0.1 on 2026-01-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0012_alter_chennairooms_futurebookings"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeseat",
            name="FutureBookings",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
