# Generated by Django 6.0.1 on 2026-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0013_officeseat_futurebookings"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinghistory",
            name="location",
            field=models.CharField(default="None", max_length=255),
        ),
    ]
