# Generated by Django 6.0.1 on 2026-01-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0014_bookinghistory_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinghistory",
            name="BookingType",
            field=models.CharField(default="None", max_length=255),
        ),
    ]
