# Generated by Django 6.0.1 on 2026-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apis", "0015_bookinghistory_bookingtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="teamName",
            field=models.CharField(default="Employee", max_length=255),
        ),
        migrations.AlterField(
            model_name="bookinghistory",
            name="location",
            field=models.CharField(default="Chennai", max_length=255),
        ),
    ]
